Feature/js19 326 initialize anime app and table view
saritasa-nest/camp-js-2022-sofya-kirillova pull request #1
Opened 2022-07-01 09:47 UTC by SofyaKirillova

2022-07-01 10:17 UTC, golovachev-yaroslav requested changes

2022-07-01 10:17 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.css
> +#sort-anime-table {
Id is unique on a page. Therefore it become not reusable. Attr `id` prefer to use if you need to do something with JS. It would be better to use CSS class, `.sort-anime-table`

2022-07-01 10:17 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/api.ts
> +import { myAxios } from './forAxios';
myAxios is not a good name, please avoid names with my, your, etc.

2022-07-01 10:17 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/api.ts
> +  currentPage: number,
I think pageNumber more clear.

2022-07-01 10:17 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/api.ts
> +  ordering: string,
And order instead of ordering.

2022-07-01 10:17 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/pagination.ts
> +  function start(apiAddress: string | undefined = undefined): void {
What's start? Not obvios name, please rename.

2022-07-01 10:17 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/pagination.ts
> +            <button>${countPages}</button>
Please add `type="button"`. Otherwise it could submit a form if it placed inside tag `form`. Also check others.

2022-07-01 10:17 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/pagination.ts
> +    highlighting();
Function is an action, need to start functions with verb.

2022-07-01 10:17 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/pagination.ts
> +      if (+elem.innerHTML === +currentPage) {
More clear` Number(elem.innerHTML) ===  Number(currentPage)`

2022-07-01 10:17 UTC, golovachev-yaroslav commented on libs/core/mappers/pagination.mapper.ts
> +    console.log(results)
Please remove. console.log needs only for debugging.

2022-07-01 11:25 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/scripts/pagination.ts
> +export function pagination(position: Element, size = 25, step = 3, page = 1): void {
Please try to restructure this function, it is very long and complicated, it is really hard to understand it.

2022-07-01 11:25 UTC, kristinaSvobodinaSaritasa commented on libs/core/models/anime.ts
> +  public readonly titleEng: string | null;
Do you really need to save null in model? Maybe map it to empty string?

2022-07-01 11:40 UTC, elena-dragunova requested changes

2022-07-01 11:40 UTC, elena-dragunova commented on apps/vanilla/src/pages/anime_table.ts
> +        <td><img class='' src='${anime.image}'></td>
Why do you add empty class?

2022-07-01 11:40 UTC, elena-dragunova commented on apps/vanilla/src/pages/index.css
> +  height: 75px;
Are you sure the content of the header will never change? Avoid using precise values for width and height. You can set your header's height with vertical paddings.
https://wiki.saritasa.rocks/frontend/languages/css#dont-set-hardcoded-size

2022-07-01 11:40 UTC, elena-dragunova commented on apps/vanilla/src/pages/index.css
> +  color: #a7a7a7;
Use variables for colors please

2022-07-01 11:40 UTC, elena-dragunova commented on apps/vanilla/src/pages/index.css
> +  outline: none;
Avoid resetting outline styles, or add some alternative solution https://wiki.saritasa.rocks/frontend/languages/css#make-sure-outline-is-not-reset-or-you-implemented-a-better-solution

2022-07-01 11:40 UTC, elena-dragunova commented on apps/vanilla/src/pages/index.html
> +    <select id="sort-anime-table">
I suppose select should be inside a form.

2022-07-01 11:40 UTC, elena-dragunova commented on apps/vanilla/src/scripts/pagination.ts
> +export function pagination(position: Element, size = 25, step = 3, page = 1): void {
Use verbs for functions names please, for example 'setPagination'

2022-07-01 11:40 UTC, elena-dragunova commented on apps/vanilla/src/scripts/pagination.ts
> +      if (+elem.innerHTML === +currentPage) {
Yes, and it's also implicit type-casting, don't use it: https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#dont-use-implicit-type-casting

2022-07-01 18:20 UTC, timofei-maximov-saritasa requested changes

2022-07-01 18:20 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/forAxios.ts
> +    baseURL: 'https://api.camp-js.saritasa.rocks/api/v1',
Please, store your `BaseURL` and `apiKey` in `.env` file. [Vite docs](https://vitejs.dev/guide/env-and-mode.html#env-variables-and-modes)

2022-07-01 18:20 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/api.ts
> +export async function apiAnimeTable(size: number,
Please, stick with [this naming pattern](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#ahclc-pattern) for your functions. Also, you don't fetch a table. You fetch an anime list. In can be rendered as list, table, cards or any other format. Come up with a better name.

2022-07-01 18:20 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/api.ts
> + * Sends a request to the database.
You don't send request to database. I can't tell what your function is doing according to docs. 
You can come up with a better function description. For example: `Fetches pagined list of anime`.

2022-07-01 18:20 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/api.ts
> + * @param https API.
Please, improve your doc string. It is not clear what is an API

2022-07-01 18:20 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/forAxios.ts
> + * Prepared data for axios.
It not a data for axios. It is preconfigured axios instance.

2022-07-01 18:20 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> + * Implementation of pagination.
Please, revise your doc strings everywhere in code.

2022-07-01 18:20 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  function start(apiAddress: string | undefined = undefined): void {
I agree with @golovachev-yaroslav. Please, revise all your function names. [Stick with](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#ahclc-pattern) it should help you

2022-07-01 18:20 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +   * Changing the sorting of the anime table.
```suggestion
   * Changes the sorting of the anime table.
```

2022-07-01 18:20 UTC, timofei-maximov-saritasa commented on libs/core/dtos/anime.dto.ts
> +    readonly end: string | null;
I guess this format can be repeated over the time. Aired can be reused in other entities. I would suggest to move this as standalone `DTO` and then use here as a type.
```ts
// aired.dto.ts
interface AiredDto {
  readonly start: string | null;
  readonly endDto | null;
}

// anime.dto.ts
/** Anime DTO. */
export interface AnimeDto {

  /** Image. */
  readonly image: string;

  /** English name. */
  readonly title_eng: string | null;

  /** Japanese name. */
  readonly title_jpn: string | null;

  /** Type. */
  readonly type: string;

  /** Status. */
  readonly status: string;

  /** Aired. */
  readonly aired: AiredDto;
}

2022-07-01 18:20 UTC, timofei-maximov-saritasa commented on libs/core/dtos/anime.dto.ts
> +  /** Image. */
Please, provide more informative description for properties.

2022-07-01 18:20 UTC, timofei-maximov-saritasa commented on libs/core/models/anime.ts
> +    start: string | null;
You keep your dates as stings, but I mentioned earlier that we keep our models as close as they are in real life. It will be easier to interact with dates if they are actual `Date` type.

2022-07-01 18:20 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  function onClick(event: Event): void {
`onClick` -> `handle*Click` by `*` I mean your button/element name. For example, `handleNextPageButtonClick`

2022-07-01 18:26 UTC, timofei-maximov-saritasa commented
Also, you have inconsistent file naming. Please, stick with one approach
<img width="195" alt="image" src="https://user-images.githubusercontent.com/86595911/176950018-befb44d2-449b-47ae-a4ac-36410b08dfcd.png">

2022-07-03 05:42 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/anime_table.ts
> +    animeData.results.forEach((anime: Anime) => {
Please do not annotate params in callbacks, it could lead to implicit type casting. You should relay on typescript inferring the type.

2022-07-03 05:42 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/functions.ts
> + * Formatted dates in dd.mm.yyyy or 'no date'.
Please use regular verbs in the present tense as if the subject is the function.
For example, we could describe function as: "The function formats date to 'dd.mm.yyyy' or 'no date'". Then we omit the subject, "The function".
In the end description would be: "Formats date to 'dd.mm.yyyy' or 'no date'".

2022-07-03 05:42 UTC, artem-sotnichenko-saritasa commented on libs/core/mappers/pagination.mapper.ts
> +    });
```suggestion
    const results = dto.results.map(anime => AnimeMapper.fromDto(anime));
```

2022-07-03 13:12 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  function onClick(event: Event): void {
Actually, it's not required to change the `on`  prefix to the `handle` one, but it's a good idea to add an element name.  We usually use `handle` prefix in React apps, `on` prefix in Angular apps, for Vaniila, it's up to you to decide, just don't violate our [naming conventions](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#naming-functions)

2022-07-04 04:43 UTC, panov-aleksey-saritasa requested changes

2022-07-04 04:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.css
> +  gap: 10px;
Don't use you using `display: grid` or `display: flex`, does `gap` work here?

2022-07-04 04:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/anime_table.ts
> +    let TABLE_HTML = `
Prefer using `const` over `let` whenever it's possible
[wiki](https://wiki.saritasa.rocks/frontend/practices/code#promote-immutability)
In this case you could make separate constants for `tableHeadElement` and `tableRowElements`, then add them to the `tableElement`

2022-07-04 04:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/api.ts
> + * Sends a request to the database.
I prefer using `obtain` or `get`  verbs instead of `fetch` , this way we omit details of how data is retrieved

2022-07-04 04:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/api.ts
> + * @returns Anime data.
Please, use `@returns` only when it's not clear what does your function return and additional explanation is needed

If `@returns` is automatically generated by VSCode, you could turn this behavior off
![image](https://user-images.githubusercontent.com/86595878/177041446-f7254219-72b8-41f0-aa1f-bbde2b0846f5.png)

2022-07-04 04:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.html
> +      <span>register</span>
Shouldn't they be links or buttons instead? If such pages or functionality are not ready yet, consider adding a [TODO](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#todo-comments) comment

2022-07-04 04:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/functions.ts
> +  if (dateReceived === null) {
I think you could put it in `core/utils` folder 🙂

2022-07-04 04:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +export function pagination(position: Element, size = 25, step = 3, page = 1): void {
It's not clear why `position` argument has `Element` type

2022-07-04 04:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +export function pagination(position: Element, size = 25, step = 3, page = 1): void {
Also if your function has more than 3 arguments, it's a sign to revise your function input. Consider, for example, combining your arguments into single object, something like `PaginationConfig`

2022-07-04 04:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +    const animePromise = apiAnimeTable(size, currentPage, ordering, apiAddress);
Rather than receive a promise, consider using `async + await` or `then` instead. What I see right now is that you are working with the same promise in the two different places (here and `animeTableOutput` function) and I don't see a reason why you need to overcomplicate things like that

2022-07-04 04:43 UTC, panov-aleksey-saritasa commented on libs/core/models/anime.ts
> +    start: string | null;
Consider creating `DateRange` type that would consist of dates

2022-07-04 04:43 UTC, panov-aleksey-saritasa commented on package.json
> +    "@types/node": "^16.11.7",
Did it fix your problem with `tsconfig`? Please, if something is not working correctly and you found a way how to fix it, write about it in `frontend-camp` Slack channel, so 1) other guys would know about how problem could be resolved and 2) we could improve this boilerplate for the future camps 🙂

2022-07-04 04:43 UTC, panov-aleksey-saritasa commented on package.json
> +    "materialize-css": "^1.0.0",
if you add this dependency to the global `package.json`, please remove `apps/vanilla/package.json` and `apps/vanilla/package-lock.json`

2022-07-04 04:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +        divHTML += `
It's not clear what `2` or `3` stand for. Please, avoid magic numbers

2022-07-04 04:43 UTC, panov-aleksey-saritasa commented on apps/vanilla/tsconfig.json
> +    "noImplicitReturns": true,
As far as I remember, `json` files do not allow trailing commas. Why do you need to this? Does it fix something?

2022-07-04 04:53 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.html
> +    <select id="sort-anime-table">
I think that the form is not needed here, since it is better to take the value directly from select

2022-07-04 05:52 UTC, maxineo approved these changes

2022-07-05 02:35 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.css
> +@import url("../global/variables.css");
In this case, it will not block parallel downloads, since in the build project all styles are combined into one file.

2022-07-05 04:52 UTC, SofyaKirillova commented on apps/vanilla/src/scripts/pagination.ts
> +export function pagination(position: Element, size = 25, step = 3, page = 1): void {
It will not be possible to combine the arguments into one object here, because there are default values. In other places, if necessary, I combined the arguments into one object

2022-07-05 05:41 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.ts
> +}
assert doesn't work. The browser writes "assert is not a function". The reason for the error was not found. It was decided to leave 'if'

2022-07-05 06:26 UTC, elena-dragunova approved these changes

2022-07-05 09:54 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/animeTable.ts
> +  });
We can achieve similar result using `reduce`. With `reduce` you can omit `let` and use `const` instead

2022-07-05 09:54 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +export function getPagination(positionPagination: HTMLDivElement, pageSize = 25, stepPage = 3, page = 1): void {
You have a lot arguments in your function. I will be hard to maintain this function. Some developers can mess up with param order. You pass element and **pagination options**. Let's improve this function by making these pagination options as an object, since you use it in `renderPagination` you can create dedicated `interface` for your options/config

2022-07-05 09:54 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  position: Element;
And with new `PaginationConfig/PaginationOptions` interface this will be reusable and it will be easier to read

2022-07-05 09:54 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/requests.ts
> + * @param https Request address.
`https` is not a good name for and url. And also, it is strange that you pass url to this function. Can you configure your request inside `getAnime` function?

2022-07-05 09:54 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  function resetPagination(apiAddress = ''): void {
Do you really need this argument?

2022-07-05 09:54 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/requests.ts
> +},
Use interfaces for complicated types. Also with interfaces you can write less docs, since you don't have to repeat documented interface properties

2022-07-06 02:26 UTC, SofyaKirillova commented on apps/vanilla/src/scripts/requests.ts
> + * @param https Request address.
Unfortunately not, since we get the url from the request.

2022-07-06 02:29 UTC, SofyaKirillova commented on apps/vanilla/src/scripts/requests.ts
> +},
We need it because if we click on the arrows (forward or backward), the url is returned to us, otherwise we use the standard url one prescribed in the getAnime function

2022-07-06 02:29 UTC, SofyaKirillova commented on apps/vanilla/src/scripts/pagination.ts
> +  function resetPagination(apiAddress = ''): void {
We need it because if we click on the arrows (forward or backward), the url is returned to us, otherwise we use the standard url one prescribed in the getAnime function

2022-07-06 02:36 UTC, pavel-romanov8 requested changes

2022-07-06 02:36 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/animeTable.ts
> +  const tableBodyHTML = animeData.results.reduce((body, current) => {
There is no need to prefix everything with `HTML`

2022-07-06 02:36 UTC, pavel-romanov8 commented on apps/vanilla/src/scripts/pagination.ts
> +    for (let i = 0; i <= countViewNumberPage; i++) {
It is really hard to read, please, consider separating your logic flow in order to reduce cognitive complexity

2022-07-06 02:36 UTC, pavel-romanov8 commented on libs/core/mappers/anime.mapper.ts
> +    const aired = AiredMapper.fromDto(dto.aired);
There is no need to create the constant, we could write it like `aired: AiredMapper.fromDto(dtoAired)`

2022-07-06 02:36 UTC, pavel-romanov8 commented on libs/core/models/pagination.ts
> +  public readonly next: string;
In case it is not a page number, please, try to improve naming for it

2022-07-06 07:31 UTC, pavel-romanov8 commented on apps/vanilla/src/scripts/pagination.ts
> +    for (let i = 0; i <= countViewNumberPage; i++) {
Forgot to share resources where you can find more info about refactoring techniques - https://refactoring.guru/refactoring

2022-07-06 13:09 UTC, chernodub commented on apps/vanilla/src/scripts/requests.ts
> + * @param paginationConfig Pagination Config: number of results to return per page, current page, selected sorting type.
No need for such detailed explanation. Revealing internals of `PaginationConfig` would be hard to refactor/maintain. Since every time you change `PaginationConfig`, you would have to go and update every documentation related to this entity

2022-07-06 13:14 UTC, chernodub commented
@SofyaKirillova please use [our convention](https://wiki.saritasa.rocks/frontend/tools/git#commit-messages) for naming commits

2022-07-07 04:34 UTC, SofyaKirillova commented on apps/vanilla/src/pages/index.html
> +    <div class="authentication">
On the contrary, I was told to create a separate class, since header can be multiple.

2022-07-07 06:14 UTC, SofyaKirillova commented on apps/vanilla/src/scripts/pagination.ts
> +  let { currentPage } = paginationOptions;
This variable is mutable.
I also changed this line a little

2022-07-07 07:34 UTC, timofei-maximov-saritasa commented on .gitignore
> +vite.config.ts
Why did you add `vite.config.ts` to your `.gitignore`?

2022-07-07 07:40 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/requests.ts
> +  /** Anime sorting mode. */
Just `Sorting mode` since it can be used for other entities

2022-07-07 07:41 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/requests.ts
> +export async function getAnime(paginationConfig: IPaginationConfig): Promise<Pagination<Anime>> {
It's a bit strange that you have async/chain syntax. Please, stick with one approach and follow it everywhere

2022-07-07 07:43 UTC, timofei-maximov-saritasa commented on libs/core/models/aired.ts
> +  /** Start date, for example, "2014-12-20T17:30:50.416Z". */
You don't need to specify date format here, since you class property has `Date` type and can be formatted in any format.

2022-07-07 07:44 UTC, timofei-maximov-saritasa commented on libs/core/models/anime.ts
> +  public readonly status: string;
These fields should be represented by `enum/union`.

2022-07-11 01:26 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/index.ts
> +  value: SortingOptions;
read-only

2022-07-11 01:26 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/index.ts
> +      value: 'aired__startswith',
I'm not sure that it was fixed. Please, don't use values BE values directly. It would be better to create mapper for them, as we discussed earlier

2022-07-11 01:26 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/pagination.ts
> + * @param paginationOptions Pagination options: count pages, current page, pages before and after current, pagination located.
There is no need to describe inner structure of your param. It should be abstracted to just `Pagination options`

2022-07-11 01:26 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/pagination.ts
> +    if (Number(elem.innerHTML) === Number(startPage)) {
Make sure you handle the case where `Number(elem.innerHTML)` is `NaN`

2022-07-11 01:26 UTC, pavel-romanov8 commented on apps/vanilla/src/scripts/mainPage.ts
> +/** Implements output and re-rendering of the anime table and pagination. */
Again, there is no need to describe the structure of the class and what it can or can't do in docs.

2022-07-11 01:26 UTC, pavel-romanov8 commented on apps/vanilla/src/scripts/unions.ts
> +export type SortingOptions = 'title_eng' | 'aired__startswith' | 'status';
The thing here is that it is not `SortingOptions`, but it's DTO.

2022-07-11 12:25 UTC, pavelzadorin-saritasa requested changes

2022-07-11 12:25 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/mainPage.ts
> +  public addEventHandlers(): void {
"addEventHandlers" has the same meaning as "addEventListener", add any handlers... `addEventListener` does exatly this, but this function does not allow you to add any handlers, think about a more accurate name.
and generally, I guess this method has to be divided to related elements, e.g. add page button listeners on paginator initialization, etc.

2022-07-11 12:25 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/mainPage.ts
> +  /** Adds event handlers to elements. */
any handlers to any elements?

2022-07-11 12:25 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/mainPage.ts
> +    const selectElement = document.querySelector<HTMLSelectElement>('.anime__sort');
you pass pagination element through the constructor, and you get the select element right here. What's the difference? Why not take a unified approach?

2022-07-11 12:25 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/mainPage.ts
> +export class MainPage {
I think it's worth discussing the need for this class, because. now the logic is strangely mixed between this class and the main code of the main page

2022-07-11 12:25 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/mainPage.ts
> +    } else if (isNaN(Number(target.innerHTML))) {
if the layout of the buttons changes, this approach will immediately break down, you don’t need to rely on innerHTML as meaningful data, for this you need to use either data-attributes

2022-07-11 12:25 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/requests.ts
> +  const url = new URLSearchParams(`limit=${paginationConfig.pageSize}&offset=${offset}&ordering=${paginationConfig.order},id`);
I think @chernodub suggest to initiate URLSearchParams by object, look example "Search parameters can also be an object" in this case your params much easier to read.

2022-07-12 05:32 UTC, SofyaKirillova commented on apps/vanilla/src/scripts/API.ts
> +import axios from 'axios';
organized the files

2022-07-13 15:23 UTC, timofei-maximov-saritasa approved these changes

2022-07-13 15:23 UTC, timofei-maximov-saritasa commented on libs/core/models/anime.ts
> +  public readonly airingFinish: Date;
According to api specification these fields are nullable. So, for example some anime title can be in ongoing status, there will be no `airingFinish`

2022-07-14 10:08 UTC, pavel-romanov8 commented on apps/vanilla/src/scripts/pagination.ts
> +  public constructor(paginationContainer: Element, startPage: number, pagesCount: number, sendCurrentPage: Function) {
`Function` is great, but it is not a very descriptive type for a function. It doesn't show that it will accept the number. Let's improve it to `(pageNumber: number) => void`

2022-07-14 10:08 UTC, pavel-romanov8 commented on apps/vanilla/src/scripts/pagination.ts
> +  public constructor(paginationContainer: Element, startPage: number, pagesCount: number, sendCurrentPage: Function) {
Also, it would be great to place each constructor argument on separate line

2022-07-14 10:08 UTC, pavel-romanov8 commented on apps/vanilla/src/scripts/pagination.ts
> +  public constructor(paginationContainer: Element, startPage: number, pagesCount: number, sendCurrentPage: Function) {
And one more thing) Since you are not using object as initializer of the class, it is recommended to initialize the class fields directly in class constructor:
```ts
public constructor(
  public readonly paginationContainer: Element,
  // other fields
) {}
```
That way we are avoiding boilerplait-ish code with initialization of each field

2022-07-14 10:08 UTC, pavel-romanov8 commented on libs/core/models/anime.ts
> +  NotYetAired = 'NOT_YET_AIRED',
Is it lowercase because of the BE sends it like that? If that is the case, I also recommend making the same mapping as you did with `AnimeSort`

2022-07-15 10:01 UTC, pavel-romanov8 approved these changes

2022-07-15 17:41 UTC, chernodub requested changes

2022-07-15 17:41 UTC, chernodub commented on apps/vanilla/src/scripts/sort.ts
> +export function initializeSort(
As I see your pagination logic is handled in a class, but here you're using functions. Please stick to a single approach, be consistent :)

2022-07-15 17:41 UTC, chernodub commented on apps/vanilla/src/scripts/sort.ts
> + * @param sendSortOrder Send the sort order.
1. Not clear where are we going to send it, I suggest you to revise the naming
2. Also, I'd recommend specifying a stricter type for a function. Something like `(sort: Sort) => void` instead of `Function`. This will make your code more robust to changes/refactoring

2022-07-15 17:41 UTC, chernodub commented on apps/vanilla/tsconfig.app.json
> +  "include": ["**/*.ts", "src/pages/constants.env"]
Hm, is this a mistake? I don't see any `constants.env` in the PR

2022-07-16 17:28 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/API.ts
> +import axios from 'axios';
any folder organizes files, but how can I understand that, for example, a new file needs to be placed exactly in this folder, what is the criterion?

2022-07-16 17:40 UTC, pavelzadorin-saritasa approved these changes

2022-07-18 03:07 UTC, SofyaKirillova commented on libs/core/dtos/anime.dto.ts
> +  };
It is unlikely that this object will be used in other parts of the project. Therefore, it is more rational not to extract the interface for this property.

2022-07-18 05:40 UTC, SofyaKirillova commented on apps/vanilla/src/scripts/pagination.ts
> +    const value = parameters.value ?? parameters.content;
The value of the button records the page number or arrow values (previous_page, next_page), so if there is no value, it means that value is equal to the page number that is written in `content` (now content has been replaced with label)

2022-07-18 18:35 UTC, chernodub commented on apps/vanilla/src/scripts/pagination.ts
> +  buttonElement.value = String(value);
[`value` can't be used without `name` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-value)

2022-07-18 18:42 UTC, chernodub commented on apps/vanilla/src/scripts/pagination.ts
> +  buttonElement.value = String(value);
for passing data that is not related to `forms`, please use [data attributes ](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes)

2022-07-18 18:43 UTC, chernodub commented on apps/vanilla/src/scripts/pagination.ts
> +}
You could use `Math.min` instead

2022-07-18 18:44 UTC, chernodub commented on apps/vanilla/src/scripts/sort.ts
> +  }, { once: true });
So, when I pick a sort, it won't work the second time?

2022-07-18 18:46 UTC, chernodub commented on apps/vanilla/tsconfig.app.json
> +  "include": ["**/*.ts", "src/pages/constants.env"]
@SofyaKirillova please do not mark comments as resolved if you didn't fix the code. In case you disagree, please leave a comment and make sure the person who left the comment saw it. You can only resolve the comment when both you and the commenter are agreed.

2022-07-20 04:48 UTC, panov-aleksey-saritasa approved these changes

2022-07-20 04:48 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.css
> +.header_login {
```suggestion
.header__login {
```

2022-07-20 04:48 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.css
> +.anime__table th {
Usually we do not mix up BEM with tag selectors

2022-07-20 04:48 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.ts
> + * Set the Current pagination page.
```suggestion
 * Set the current pagination page.
```

2022-07-20 04:48 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/interfaces.ts
> +  paginationContainer: Element;
Missing `readonly`?

2022-07-20 04:48 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/requests/animeList.ts
> +  const order = AnimeSortMapper.toDto(paginationConfig.order);
```suggestion
export async function getAnimeList(paginationConfig: PaginationConfig): Promise<Pagination<Anime>> {
  const order = AnimeSortMapper.toDto(paginationConfig.order);
```

2022-07-20 04:48 UTC, panov-aleksey-saritasa commented on libs/core/utils/formatDate.ts
> +  }
Consider returning `null` here, so consumers of this function could handle cases when date is not correct by themselves

2022-07-20 05:09 UTC, SofyaKirillova commented on libs/core/utils/formatDate.ts
> +  }
All consumers will render  'No date', so it is irrational to return null instead of 'No date'.

2022-07-21 03:44 UTC, merged