Feature/jc19 469 anime list react
saritasa-nest/camp-js-2022-sofya-kirillova pull request #10
Opened 2022-08-22 11:18 UTC by SofyaKirillova

2022-08-22 12:05 UTC, golovachev-yaroslav requested changes

2022-08-22 12:05 UTC, golovachev-yaroslav commented on libs/core/mappers/genre.mapper.ts
> +    // console.log(fromDtoMapType[dto.type])
Please remove.

2022-08-23 10:54 UTC, artem-sotnichenko-saritasa commented on apps/react/src/api/interceptors/authInterceptor.ts
> +export const addTokenBeforeRequest = (config: AxiosRequestConfig): AxiosRequestConfig => {
https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#use-function-declaration

2022-08-23 10:54 UTC, artem-sotnichenko-saritasa commented on apps/react/src/api/services/anime.ts
> +    return PaginationMapper.fromDto(data, AnimeCommonMapper.fromDto);
It looks repetitive, you could conditionally set only api url.

2022-08-23 10:54 UTC, artem-sotnichenko-saritasa commented on apps/react/src/api/services/local-storage.ts
> +  export const setLocalStorage = (token?: Token | null): void => {
Please rethink your naming.
`getSessionToken` is obviously about token, but why `setLocalStorage` works only with token? Please rename it or refactor it.

2022-08-23 10:54 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/components/AnimeShort/AnimeShort.module.css
> +  background-color: #757ce8;
I see that you used variables for colors, please be consistent.

2022-08-23 10:54 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.module.css
> +  height: calc(100vh - 35px);
Consider moving header height into global variable, or find a way not to use `vh`(if possible).

2022-08-23 10:54 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +            hasMore={true}
It shouldn't be hardcoded, to fix it, I suggest creating field in the store

2022-08-23 10:54 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +            ))}
You shouldn't annotate it, because if type become wrong in the future, you wouldn't know.

2022-08-23 10:54 UTC, artem-sotnichenko-saritasa commented on apps/react/src/index.tsx
> +  <App />,
Can you explain why you disabled strict mode?

2022-08-23 10:54 UTC, artem-sotnichenko-saritasa commented on apps/react/src/routes/guards/auth-guard.tsx
> +  if (isLoading === true) {
You can omit comparing boolean to a boolean

2022-08-23 10:54 UTC, artem-sotnichenko-saritasa commented on apps/react/src/store/anime/state.ts
> +  readonly countAnime: number;
I think you can name it just `count`, because it's **anime** state.

2022-08-23 11:16 UTC, golovachev-yaroslav requested changes

2022-08-23 11:16 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/pages/LoginPage/LoginPage.tsx
> +import { useNavigate } from 'react-router-dom';
Let's import external libs as the first and then developer's.

2022-08-23 11:16 UTC, golovachev-yaroslav commented on apps/react/src/store/auth/dispatchers.ts
> +  'auth/fetch',
'auth/fetch' - not obvious, let's rename to 'auth/fetchUser'

2022-08-24 08:25 UTC, SofyaKirillova commented on apps/react/src/index.tsx
> +  <App />,
It was found that `StrictMode` doubles the rendering of the page. Therefore it was decided to remove it.

2022-08-24 15:14 UTC, timofei-maximov-saritasa commented on apps/react/src/index.tsx
> +  <App />,
@SofyaKirillova Please `StrictMode` docs, double render is intended https://reactjs.org/docs/strict-mode.html

2022-08-29 08:00 UTC, closed without merging