Feature/jc19 343 authentication
saritasa-nest/camp-js-2022-sofya-kirillova pull request #2
Opened 2022-07-11 10:06 UTC by SofyaKirillova

2022-07-13 04:39 UTC, timofei-maximov-saritasa requested changes

2022-07-13 04:39 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/registration.ts
> +  const h5Element = document.querySelector('.registration__error');
Context for this element may be lost in big functions, because it is not obvious what is `h5Element` responsible for.    Let's rename.

2022-07-13 04:41 UTC, panov-aleksey-saritasa requested changes

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/authentication/authorization.html
> +    <h2>Authorization</h2>
Please, do not skip heading levels
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#usage_notes

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on apps/vanilla/package.json
> +{
Local `package.json` files could exist in monorepos, but there should be a reason behind it, for example, if you need different version of dependency for specific app or lib.
But in your case I don't understand why do you need it. Please, explain

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/authentication/authorization.ts
> +      const h5Element = document.querySelector('.authorization__error');
Prefer more semantic names, `h5Element` is too generic and implicit

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/authentication/registration.html
> +    <h2>Registration</h2>
Same about skipping heading levels

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/authentication/registration.html
> +      <input name="last-name" type="text" id="last_name">
To avoid managing `for` and `id` attributes, you could just put the `input` tag inside the `label`

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/authentication/authentication.css
> +}
What does `di` mean? 🤔

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.ts
> +  }
You can just use generic: `document.querySelector<HTMLTemplateElement>('#unauthorized')`

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/requests/authorization.ts
> +      displayTheError(error.detail, h5Element);
Your business logic shouldn't know anything about UI. Please, delegate error handling to consumers of `authentication` function

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/requests/authorization.ts
> +  await api.post(`/auth/login/`, formData).then(res => {
https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#dont-mix-approaches-to-work-with-promises

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/requests/authorization.ts
> +export async function authentication(formData: FormData): Promise<void> {
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#ahclc-pattern

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/requests/authorization.ts
> +export async function authentication(formData: FormData): Promise<void> {
Using `FormData` as argument type is almost the same as using `any`. I mean you could pass here any form data object. Consider creating interface and narrowing this type to something more specific, like `AuthData`

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/requests/refreshToken.ts
> +export async function updateToken(): Promise<boolean> {
It's not clear why the function that update a token, returns `boolean`. It's a good a place to add `@returns` JSDoc tag

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/registration.ts
> +  '%2Ff33c09a7-a15e-4b7c-b47f-650bfe19faff%2Fprofile.jpg';
Rather hardcoding this URL, consider adding it your repo as asset.

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on libs/core/mappers/fieldError.mapper.ts
> +export namespace GenreMapper {
```suggestion
export namespace FieldErrorMapper {
```

2022-07-13 04:41 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/registration.ts
> +  '%2Ff33c09a7-a15e-4b7c-b47f-650bfe19faff%2Fprofile.jpg';
Also, how about letting users load any avatar they want? 🙃

2022-07-13 05:07 UTC, gevorg-gevorgyan-saritasa requested changes

2022-07-13 05:07 UTC, gevorg-gevorgyan-saritasa commented on libs/core/utils/functions.ts
> +  container.classList.remove('di');
Rename this class, please

2022-07-13 05:07 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/scripts/fillFields.ts
> +export function fillFields(formData: FormData): boolean{
```suggestion
export function fillFields(formData: FormData): boolean {
```

2022-07-13 05:07 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/scripts/fillFields.ts
> +export function fillFields(formData: FormData): boolean{
And also think about renaming this function, because the current name says that this function fills some fields, but based on the docs, it checks them for emptiness

2022-07-13 06:48 UTC, golovachev-yaroslav requested changes

2022-07-13 06:48 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/authentication/registration.html
> +  <title>Vite App</title>
This title should be related to registration.

2022-07-13 06:48 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.html
> +
PLease remove empty rows.

2022-07-14 06:04 UTC, elena-dragunova requested changes

2022-07-14 06:04 UTC, elena-dragunova commented on apps/vanilla/src/requests/authorization.ts
> +export async function authentication(userData: FormData): Promise<void> {
We usually use verbs for functions, for example you can use 'login' here.

2022-07-15 08:31 UTC, SofyaKirillova commented on apps/vanilla/src/scripts/registration.ts
> +  '%2Ff33c09a7-a15e-4b7c-b47f-650bfe19faff%2Fprofile.jpg';
The request requires a link that the site provides after image processing.

2022-07-15 09:21 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/requests/registration.ts
> +      displayTheError(Object.values(error.data)[0][0], h5Element);
Please think for a better name, in a future tag of `.registration__error` can change, and variable name would be misleading.

2022-07-15 09:21 UTC, artem-sotnichenko-saritasa commented on libs/core/utils/functions.ts
> +  if (value === null || value === undefined) {
In saritasa we prefer this.
```suggestion
  if (value == null) {
```

2022-07-20 05:19 UTC, elena-dragunova approved these changes

2022-07-20 05:22 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/requests/authorization.ts
> +export async function login(authData: FormData): Promise<void | FieldError> {
Seems like https://github.com/saritasa-nest/camp-js-2022-sofya-kirillova/pull/2#discussion_r919637744 is unresolved

2022-07-20 05:22 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.ts
> +  const isTokenValid = await verifyToken();
I think UI should't know anything about tokens stuff. Maybe it should check whether is authorized or not instead

2022-07-20 05:22 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/requests/refreshToken.ts
> +  );
So every time `updateToken` is called, two new interceptors are added, but the old interceptors do not disappear anywhere. Are you sure it's a good approach?

2022-07-20 05:22 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/requests/registration.ts
> +    window.location.replace('/');
I think it would be better to delegate navigation stuff to consumers of `register` function.

2022-07-20 05:22 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/requests/verifyToken.ts
> +}
I think more elegant solution is to move out this stuff to to interceptors.

2022-07-20 05:22 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/requests/verifyToken.ts
> +  await api.post(`/auth/token/verify/`, { token: accessToken }).then(() => {
As I said before, please, do not mix `await` and `then`
https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#dont-mix-approaches-to-work-with-promises

2022-07-20 11:11 UTC, gevorg-gevorgyan-saritasa requested changes

2022-07-20 11:11 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/requests/verifyToken.ts
> +  let isVerifyToken = false;
Rename it to `isTokenValid`, as you  did in `index.ts`

2022-07-20 11:11 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/authentication/authorization.ts
> +  const isFillFields = checkFieldsEmptiness(formData);
I think this name is not quite readable. Maybe rename it to `isFormFilled`? I guess the meaning will remain the same

2022-07-20 11:11 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/authentication/registration.ts
> +  if (isFillFields === false) {
This is `boolean`, so you can just use `!`

2022-07-20 11:11 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/index.ts
> +  if (isTokenValid === true) {
```suggestion
  if (isTokenValid) {
```

2022-07-20 11:11 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/authentication/authentication.css
> +  row-gap: 25px;
Try to avoid using `row-gap` if it's possible.

2022-07-20 15:17 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/global/base.css
> +  margin: auto;
You can use only the margin shorthand: 
margin: 0 auto 25px;

2022-07-21 03:28 UTC, maxineo commented on apps/vanilla/src/requests/authorization.ts
> + * @param authData Sends a request for user authorization.
Please improve the description. Right now its kinda misleading.

2022-08-04 15:19 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-29 08:00 UTC, closed without merging