Feature/js19 366 type filtering
saritasa-nest/camp-js-2022-sofya-kirillova pull request #3
Opened 2022-07-14 06:02 UTC by SofyaKirillova

2022-07-14 06:16 UTC, elena-dragunova requested changes

2022-07-14 06:16 UTC, elena-dragunova commented on apps/vanilla/src/scripts/typeFilter.ts
> +export function initializationTypeFilter(
Use verbs for functions please.
You can use 'initializeTypeFiltering' for example.

2022-07-16 10:17 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/requests/animeList.ts
> +
Please remove empty line

2022-07-16 10:17 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +
Please be consistent with formatting, if this empty lines don't have meaning, remove them.

2022-07-16 10:17 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +
I seen a lot of stray empty lines, please pay more attention to it.

2022-07-18 08:28 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/typeFilter.ts
> +}
This function should be located near your model

2022-07-18 08:28 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/typeFilter.ts
> +function addListenersToSort(filterContainer: Element, sendValue: Function): void {
Please, don't use `Function` type, since it's not type safe. You can pass any function here. You can declare type for the function
```ts
type SomeFunction = (value: string) => void
```

2022-07-18 08:28 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/typeFilter.ts
> +  const typeContent: FieldOptions<Type | null>[] = [
Missing readonly

2022-07-20 05:25 UTC, elena-dragunova approved these changes

2022-07-21 19:10 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-21 19:10 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> + * @param event The pressed button.
Add description

2022-07-21 19:22 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +}
You can use `Math.min`

2022-07-21 19:22 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  buttonElement.className = parameters.label === parameters.startPage ?
Don't forget to add `type` attribute for button
https://wiki.saritasa.rocks/frontend/languages/html#type-for-button

2022-07-21 19:22 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/typeFilter.ts
> +    }
```suggestion
    const type = checkIsType(typeContainer.value) ? typeContainer.value : null;
```

2022-08-29 08:00 UTC, closed without merging