Feature/jc19 397 initialize anime table view angular
saritasa-nest/camp-js-2022-sofya-kirillova pull request #5
Opened 2022-07-25 10:19 UTC by SofyaKirillova

2022-07-26 03:11 UTC, dmitriqm requested changes

2022-07-26 06:09 UTC, timofei-maximov-saritasa requested changes
Anime-related logic should placed inside `anime-module` according to task

2022-07-26 06:09 UTC, timofei-maximov-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +/** Anime server. */
```suggestion
/** Anime service. */
```

2022-07-26 13:39 UTC, gevorg-gevorgyan-saritasa requested changes

2022-07-26 13:39 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +    private http: HttpClient,
Missing `readonly`

2022-07-26 13:39 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> +    private animeServer: AnimeService,
```suggestion
    private readonly animeService: AnimeService,

2022-07-26 13:39 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> +  public animeTable$: Observable<readonly Anime[]>;
`readonly`

2022-07-27 04:04 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-27 04:04 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +import { Anime } from '@js-camp/core/models/anime';
Please place imports tightly.

2022-07-29 02:57 UTC, kristinaSvobodinaSaritasa approved these changes

2022-07-29 03:13 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime.component.ts
> +   * The function formats date to 'dd.mm.yyyy' or 'no date'.
There is no need to describe what the inner function do

2022-07-29 03:13 UTC, pavel-romanov8 commented on libs/core/tsconfig.app.json
> +  "include": ["**/*.ts", ]
Is it really necessary to leave this comma?

2022-07-29 03:13 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime.component.html
> +        <img class="anime__image" src="{{row.image}}" alt="image">
The `image` is not very informative alt text. I believe it would be better to leave something like _image of anime {animeTitle}_ or something like that

2022-07-29 06:17 UTC, dmitriqm approved these changes

2022-07-29 13:29 UTC, dbitkovski requested changes

2022-07-29 13:29 UTC, dbitkovski commented on apps/angular/src/app/app.component.html
>  <router-outlet></router-outlet>
I'm interested where you will add a page to create / edit anime :roll_eyes: 
Almost all SPA uses routing because without it you can properly manage your app. Let's use it also, I think it's better to change navigation now then spending time when you have another task with managing anime :)

2022-07-29 13:29 UTC, dbitkovski commented on apps/angular/src/app/app.module.ts
> +  declarations: [AppComponent, AnimeComponent, FormatDatePipe],
According to the [task](https://saritasa.atlassian.net/browse/JC19-392) you have to create a module for all anime related features

2022-07-29 13:29 UTC, dbitkovski commented on apps/angular/src/core/interceptors/BaseInterceptor.ts
> +      url: environment.apiUrl + req.url,
Like this idea :+1:

2022-07-29 13:29 UTC, dbitkovski commented on apps/angular/src/shared/pipes/formatDate.ts
> +export class FormatDatePipe implements PipeTransform {
Honestly, I don't think it's a good idea to have such pipe. Angular `DatePipe` covers different cases and can work with different locales so let it do its work.
If you still want to use your pipe consider injecting `DatePipe` into this one and work with it directly to not add extra logic

2022-08-02 04:45 UTC, chernodub approved these changes

2022-08-02 04:45 UTC, chernodub commented on apps/angular/src/app/app-routing.module.ts
> +  providers: [{ provide: LocationStrategy, useClass: PathLocationStrategy }],
Do you really need to override the defaults here? Consider either removing or documenting this behavior, please

2022-08-02 04:45 UTC, chernodub commented on apps/angular/src/app/app.component.css
> +}
Instead of relying on library classes, please consider adding your own custom class. This way, if Angular team changes their class names, your code won't be affected. I recommend always keeping that in mind when relying on the internals of APIs and libraries.

2022-08-02 04:45 UTC, chernodub commented on apps/angular/src/app/app.module.ts
> +import { httpInterceptorProviders } from '../core/interceptors/httpInterceptorProviders';
Please stick to angular convention when naming files https://angular.io/guide/styleguide#separate-file-names-with-dots-and-dashes

2022-08-02 04:45 UTC, chernodub commented on apps/angular/src/app/features/anime/anime.component.css
> +}
Like I recommended before, please avoid relying on the library-provided classes

2022-08-02 04:45 UTC, chernodub commented on apps/angular/src/app/features/anime/anime.component.css
> +  max-height: 150px;
What if the image provided by the API is less than 150px, let's say 50px? Consider handling that case too

2022-08-02 04:45 UTC, chernodub commented on apps/angular/src/app/features/anime/anime.component.html
> +<div class="anime">
Are you sure you need this intermediate wrapper? I think you could unload your markdown and only use a table

2022-08-02 04:45 UTC, chernodub commented on apps/angular/src/app/features/anime/anime.component.ts
> +  public constructor(animeServer: AnimeService) {
Probably there's a typo, it's service, not server

2022-08-02 04:45 UTC, chernodub commented on apps/angular/src/core/interceptors/BaseInterceptor.ts
> +export class BaseInterceptor implements HttpInterceptor {
That's not a good name for an interceptor. We could have multiple interceptors in our application, each of them could do different things. The names of these interceptors should be representative so that we could easily distinguish them. Please make it more specific. To improve your naming skills, you should always think from a perspective of a code reader. For example, a dev that opened `httpInterceptorProviders` file, how would they understand which interceptors are used and what do they do?

2022-08-02 04:45 UTC, chernodub commented on apps/angular/src/core/interceptors/BaseInterceptor.ts
> +      url: environment.apiUrl + req.url,
Usually, we recommend creating an interlayer service for obtaining env values (let's say `AppConfigService`). This way, we are able to seamlessly change env handling without affecting/refactoring the application internals. For example, sometimes applications call `process.env` for environment variables.

2022-08-10 03:23 UTC, pavel-romanov8 commented on libs/core/models/anime.ts
> +// export type AnimeType = 'TV' | 'OVA' | 'Movie' | 'Special' | 'ONA' | 'Music';
Please, remove dead code

2022-08-10 03:23 UTC, pavel-romanov8 commented on libs/core/models/animeSort.ts
> +  Descending = '-',
It is super strange values for direction, please, leave some comments on why you are doing so

2022-08-16 03:40 UTC, dbitkovski approved these changes

2022-08-16 03:40 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime.component.html
> +  [trackBy]="trackAnime" matSort aria-label="Anime table">
If you have more than 3 attributes, please put each on a separate line

2022-08-16 03:40 UTC, dbitkovski commented on libs/core/models/animeSort.ts
> +}
Instead of making separate interface for anime sort I would recommend having generic `Sort` model. `order` property would be `T` type which you might pass as generic parameter. So your `AnimeSort` transforms to `Sort<AnimeSortFields>`.
Since `Sort<>` interface is the same for all sorting it's better to have only one model. Also you won't need a lot of mapper classes then

2022-08-26 02:45 UTC, merged