Feature/jc19 404 anime list management angular
saritasa-nest/camp-js-2022-sofya-kirillova pull request #6
Opened 2022-07-29 05:02 UTC by SofyaKirillova

2022-07-29 11:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/anime.component.css
> +  width: 65%;
I see that you're copying page width. I suggest to create one source of truth, a page width variable in `:host`.

2022-07-29 11:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> +    private animeServer: AnimeService,
Don't forget to add readonly

2022-07-29 11:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> +      switchMap(() => this.animeServer.fetchAnime(animeQueryParams)),
Please rename `animeServer` `animeService`.It is our preferred naming

2022-07-29 11:54 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> +    return timer(fetchDelayInMilliseconds).pipe(
Do you really need a delay? I think what you need is to use a `debounce` operator, read about it.

2022-07-31 09:15 UTC, gevorg-gevorgyan-saritasa requested changes

2022-07-31 09:15 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> +    this.anime$ = route.queryParams.pipe(
Actually a think it would be better if you use your sort / filter / search / pagination changes to fetch anime list, not query params. Consider creating `FormControl` for your search input and filter select, and something for pagination and sorting. 

Then you will be able to detect their changes with `Observable`, and combine them inside a constructor to fetch your anime list. Also it will allow you to get rid of search and filter change hadlers methods

2022-08-02 04:49 UTC, chernodub commented
@SofyaKirillova I see some of the changes are duplicated with #5, please set the #5 as a base of this PR

2022-08-02 11:47 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> +    switch (sort.direction) {
```suggestion
    const direction = sort.direction === 'desc' ? Direction.Descending :  Direction.Ascending;
    this.addParametersToUrl({ ordering: sort.active, direction });
```

2022-08-02 11:47 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> +  public applyType(types: MatSelectChange): void {
Maybe rename to applyFilter, from my opinion it will be more consistent.

2022-08-02 11:47 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/core/services/anime.service.ts
> +    const url = new HttpParams()
Why `url`?

2022-08-05 08:31 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +    const types = params.types !== [] ?
I think `params.types.length > 0` will look more readable.

2022-08-05 08:31 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> +  /** Count of anime in the database. */
I dont think you need to mention database here.

2022-08-05 09:15 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> +  ];
I suggest using `Object.values` of `AnimeType`, that way array will contain all anime types, event if you extend `AnimeType`.

2022-08-05 09:15 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +    const types = params.types !== [] ?
You can't compare reference data types like this. It will always be true.

2022-08-05 09:37 UTC, chernodub commented on apps/angular/src/app/features/anime/anime.component.ts
> +  /** Count of anime in the database. */
@gevorg-gevorgyan-saritasa please specify **why** :)

2022-08-05 10:08 UTC, chernodub requested changes

2022-08-05 10:08 UTC, chernodub commented on apps/angular/src/app/features/anime/anime.component.ts
> +      direction: this.route.snapshot.queryParamMap.get(NameAnimeParams.SortingDirection) as SortDirection ?? 'asc',
I see that you're operating directly with the values that BE provides. Consider the following example, BE decides that they want to use `Ascending` instead of `asc`. What you'd do? You would have to go and change several components/services in your application. Not cool. That's why we map BE-provided information to our own. For your case, you could create some enum that would logically have the same values e.g.: `enum SortDirection {Ascending, Descending}`. But then it could be mapped to what BE expects. This would uncouple your code from BE, which is easier to maintain and refactor

2022-08-05 10:19 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> +  /** Count of anime in the database. */
I don't think it's good to write something about database / server / backend inside components, even in docs. Components shouldn't know that.

2022-08-08 09:47 UTC, dbitkovski approved these changes

2022-08-08 09:47 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime.component.html
> +  <div *ngIf="isLoading$ | async">
I think you can apply `*ngIf` for `mat-progress-bar` and remove extra div

2022-08-08 09:47 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime.component.ts
> +  public isLoading$ = new BehaviorSubject<boolean>(false);
Don't forget to mark you properties as `readonly` if they're not supposed to be re-assigned since we [promote immutability](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#promote-immutability)

2022-08-11 07:41 UTC, chernodub approved these changes

2022-08-11 07:41 UTC, chernodub commented on apps/angular/src/app/features/anime/anime.component.css
>  .anime__image {
Seems like [this comment](https://github.com/saritasa-nest/camp-js-2022-sofya-kirillova/pull/6#discussion_r938648767) was not addressed. The layout is still jumping, please set fixed size of the images or aspect-ratio

https://user-images.githubusercontent.com/37013688/184085397-995842e1-3471-45b4-8cc3-687f40802400.mov

2022-08-11 07:41 UTC, chernodub commented on apps/angular/src/app/features/anime/anime.component.ts
> +  } as const;
usually we prefer to keep our construction section as simple as possible, so that the properties of the component would be easily distinguishable. For this case, you could move this into a function

2022-08-11 14:44 UTC, dbitkovski approved these changes

2022-08-12 01:49 UTC, pavel-romanov8 approved these changes

2022-08-12 01:49 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime.component.css
>  .anime__image {
@SofyaKirillova You can read a great article by Jake Archibald about the difference between `aspect-ratio` and fixed size - https://jakearchibald.com/2022/img-aspect-ratio/

2022-08-12 01:49 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime.component.ts
> +enum NameAnimeParams {
It sounds more like a function, let's improve it to
```suggestion
enum AnimeParamName {
```
And please, use singular forms for enums because it is representing 1 parameter at a time

2022-08-12 01:49 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime.component.ts
> +  } as const;
Also, from the perspective of a person you read the code, it is a lot easier to read it when it looks like this
```ts
public readonly defaultAnimeParams: AnimeParams; // or whatever type you have
``` 
We can instantly see the type of component filed and be able to match it with other logic instead of keeping the type in our minds

2022-08-12 01:49 UTC, pavel-romanov8 commented on apps/angular/src/core/interfaces/AnimeQueryOptions.ts
> +  readonly types: AnimeType[];
Can it be a read-only array?

2022-08-12 06:50 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-08-26 03:09 UTC, merged