Feature/jc19 459 initialize anime app and authorization feature react
saritasa-nest/camp-js-2022-sofya-kirillova pull request #9
Opened 2022-08-22 03:30 UTC by SofyaKirillova

2022-08-22 05:05 UTC, golovachev-yaroslav requested changes

2022-08-22 05:05 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/components/LoginForm/formSettings.ts
> +import * as Yup from 'yup';
Ususlly import external libs, then developer's.

2022-08-22 05:05 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/pages/LoginPage/LoginPage.tsx
> +        <Box component="form" noValidate onSubmit={formik.handleSubmit}>
It would be better to use `<Form>` component from `formik`. This is more semantic.

2022-08-24 04:30 UTC, pavelzadorin-saritasa requested changes

2022-08-29 08:00 UTC, closed without merging